# Generated by Django 4.1.2 on 2022-10-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdid', models.CharField(max_length=20, unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('bot', models.ManyToManyField(related_name='student', to='bots.bot')),
            ],
            options={
                'verbose_name': 'Учащийся',
                'verbose_name_plural': 'Учащиеся',
                'ordering': ('last_name',),
            },
        ),
    ]
