# Generated by Django 4.1.2 on 2022-11-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bot',
            field=models.ManyToManyField(related_name='student', to='bots.bot', verbose_name='Бот'),
        ),
    ]
