# Generated by Django 4.1.2 on 2022-11-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentbot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentbot',
            constraint=models.UniqueConstraint(fields=('bot', 'student'), name='unique_StudentBot'),
        ),
    ]
