# Generated by Django 4.1.2 on 2022-10-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_bot_options_rename_active_bot_is_active_and_more'),
        ('users', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bot',
            field=models.ManyToManyField(related_name='student', to='bots.bot', verbose_name='Бот'),
        ),
    ]
