# Generated by Django 4.1.2 on 2022-11-12 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('users', '0003_studentbot_unique_studentbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbot',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='bots.bot', verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='studentbot',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='users.student', verbose_name='Учащийся'),
        ),
    ]
