# Generated by Django 4.1.2 on 2022-10-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminbot',
            old_name='tdid',
            new_name='tgid',
        ),
    ]
