# Generated by Django 4.1.2 on 2022-10-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_tdid_adminbot_tgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbot',
            name='pin',
            field=models.SlugField(blank=True),
        ),
    ]
