# Generated by Django 4.1.2 on 2022-11-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('users', '0004_alter_studentbot_bot_alter_studentbot_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bot',
            field=models.ManyToManyField(through='users.StudentBot', to='bots.bot'),
        ),
        migrations.AlterField(
            model_name='studentbot',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.bot', verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='studentbot',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Учащийся'),
        ),
    ]
