# Generated by Django 4.1.2 on 2022-11-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_adminbot_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='tdid',
            new_name='tgid',
        ),
        migrations.AddField(
            model_name='student',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Last login time'),
        ),
    ]
