# Generated by Django 4.1.2 on 2022-12-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_bot_alter_studentbot_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
