# Generated by Django 4.1.2 on 2022-11-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_tdid_student_tgid_student_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Активирован?'),
        ),
    ]
