# Generated by Django 4.1.2 on 2022-11-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_student_is_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbot',
            name='pin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
