# Generated by Django 4.1.2 on 2022-11-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_adminbot_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbot',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
