# Generated by Django 4.1.2 on 2022-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_adminbot_state_student_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbot',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
