# Generated by Django 4.1.2 on 2022-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Обычный - 1'), ('2', 'Трудный - 2'), ('3', 'Для гениев - 3')], default='1', max_length=1, verbose_name='Трудность задания'),
        ),
    ]
