# Generated by Django 4.1.2 on 2022-12-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_task_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(verbose_name='Дата ответа'),
        ),
    ]
