# Generated by Django 4.1.2 on 2022-12-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(choices=[(1, '1 месяц'), (3, '3 месяца'), (5, '5 месяцев'), (9, '9 месяцев'), (10, '10 месяцев')], verbose_name='Тарифы')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Стоимость тарифа')),
            ],
        ),
    ]
