# Generated by Django 4.1.2 on 2022-12-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarif',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
    ]
