# Generated by Django 4.1.2 on 2022-11-12 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Telegram token')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Telegram username')),
                ('name', models.CharField(max_length=100, verbose_name='Имя бота')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен?')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль бота')),
                ('days', models.CharField(choices=[('WORKING_DAYS', 'Рабочие дни'), ('WEEK', 'Вся неделя')], default='WEEK', max_length=20, verbose_name='Дни работы')),
                ('hours', models.CharField(blank=True, max_length=100, verbose_name='Часы запуска')),
                ('is_show_wrong_right', models.BooleanField(default=True, verbose_name='Показывать Правильно-Неправильно?')),
                ('is_show_answer', models.BooleanField(default=True, verbose_name='Показывать правильный ответ?')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='users.adminbot', verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
    ]
