# Generated by Django 4.1.2 on 2022-10-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Telegram token')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Telegram username')),
                ('name', models.CharField(max_length=100, verbose_name='Имя бота')),
                ('active', models.BooleanField(default=False, verbose_name='Активен?')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='users.adminbot', verbose_name='Администратор')),
            ],
        ),
    ]
