# Generated by Django 4.1.2 on 2022-10-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='bot',
            name='password',
            field=models.CharField(default=1, max_length=50, verbose_name='Пароль бота'),
            preserve_default=False,
        ),
    ]
