# Generated by Django 4.1.2 on 2022-11-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_allow_again',
            field=models.BooleanField(default=False, verbose_name='Разрешить повторно ответить?'),
        ),
    ]
