# Generated by Django 4.1.2 on 2022-11-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_show_answer',
            field=models.BooleanField(default=True, verbose_name='Показывать правильный ответ?'),
        ),
        migrations.AddField(
            model_name='bot',
            name='is_show_wrong_right',
            field=models.BooleanField(default=True, verbose_name='Показывать Правильно-Неправильно?'),
        ),
    ]
