# Generated by Django 4.1.2 on 2022-10-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_bot_options_rename_active_bot_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='days',
            field=models.CharField(blank=True, choices=[('workingday', 'Рабочие дни'), ('week', 'Вся неделя')], max_length=20, verbose_name='Дни работы'),
        ),
        migrations.AddField(
            model_name='bot',
            name='hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='Часы запуска'),
        ),
    ]
