# Generated by Django 4.1.2 on 2022-11-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_is_allow_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='tz',
            field=models.CharField(choices=[('KLG', 'Europe/Kaliningrad +02'), ('MSK', 'Europe/Moscow +03'), ('SMR', 'Europe/Samara +04'), ('YKB', 'Asia/Yekaterinburg +05'), ('OMS', 'Asia/Omsk +06'), ('KRY', 'Asia/Krasnoyarsk +07'), ('IRK', 'Asia/Irkutsk +08'), ('CHT', 'Asia/Chita +09'), ('VDV', 'Asia/Vladivostok +10'), ('MGD', 'Asia/Magadan +11'), ('KMK', 'Asia/Kamchatka +12')], default='MSK', max_length=20, verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='is_allow_again',
            field=models.BooleanField(default=False, verbose_name='Разрешить ответить повторно?'),
        ),
    ]
