# Generated by Django 4.1.2 on 2022-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot_days_bot_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='days',
            field=models.CharField(choices=[('workingday', 'Рабочие дни'), ('week', 'Вся неделя')], default=None, max_length=20, verbose_name='Дни работы'),
        ),
    ]
