# Generated by Django 4.1.2 on 2022-11-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot_tz_alter_bot_is_allow_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='tz',
            field=models.CharField(choices=[('Europe/Kaliningrad', 'Europe/Kaliningrad +02'), ('Europe/Moscow', 'Europe/Moscow +03'), ('Europe/Samara', 'Europe/Samara +04'), ('Asia/Yekaterinburg', 'Asia/Yekaterinburg +05'), ('Asia/Omsk', 'Asia/Omsk +06'), ('Asia/Krasnoyarsk', 'Asia/Krasnoyarsk +07'), ('Asia/Irkutsk', 'Asia/Irkutsk +08'), ('Asia/Chita', 'Asia/Chita +09'), ('Asia/Vladivostok', 'Asia/Vladivostok +10'), ('Asia/Magadan', 'Asia/Magadan +11'), ('Asia/Kamchatka', 'Asia/Kamchatka +12')], default='Europe/Moscow', max_length=20, verbose_name='Часовой пояс'),
        ),
    ]
