# Generated by Django 4.1.2 on 2022-11-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_bot_tz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='is_allow_again',
        ),
    ]
