# Generated by Django 4.1.2 on 2022-11-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_bot_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='days',
            field=models.CharField(choices=[('WORKING_DAYS', 'Рабочие дни'), ('WEEK', 'Вся неделя')], default='WEEK', max_length=20, verbose_name='Дни работы'),
        ),
    ]
