# Generated by Django 4.1.2 on 2022-12-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_remove_bot_is_allow_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='password',
            field=models.CharField(max_length=500, verbose_name='Пароль бота'),
        ),
    ]
