# Generated by Django 4.1.2 on 2022-12-16 19:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifs', '0002_alter_tarif_options'),
        ('bots', '0006_alter_bot_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата конца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено?'),
        ),
        migrations.AddField(
            model_name='bot',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='tarif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='tarifs.tarif', verbose_name='Тариф'),
        ),
    ]
