# Generated by Django 4.1.2 on 2022-12-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_bot_end_time_bot_is_paid_bot_start_time_bot_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата конца тарифа'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата начала тарифа'),
        ),
    ]
