# Generated by Django 4.1.2 on 2022-12-16 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_alter_bot_end_time_alter_bot_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата конца тарифа'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала тарифа'),
        ),
    ]
