# Generated by Django 4.1.2 on 2022-12-17 06:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_alter_bot_end_time_alter_bot_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2100, 12, 31, 0, 0), verbose_name='Дата конца тарифа'),
        ),
    ]
