# Generated by Django 4.1.2 on 2022-12-17 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifs', '0006_alter_tarif_duration'),
        ('bots', '0011_alter_bot_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='tarif',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='tarifs.tarif', verbose_name='Тариф'),
        ),
    ]
