# Generated by Django 4.1.2 on 2023-02-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0012_bot_last_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="last_rating",
            field=models.CharField(
                max_length=10, verbose_name="Дата последнего рейтинга"
            ),
        ),
    ]
