# Generated by Django 4.1.2 on 2022-11-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgid', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('org', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=100)),
                ('why', models.CharField(max_length=1000)),
                ('state', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
