# Generated by Django 4.1.2 on 2022-11-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp',
            old_name='chat',
            new_name='tgid',
        ),
    ]
