# Generated by Django 4.1.2 on 2022-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regbot', '0003_temp_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
