# Generated by Django 4.1.2 on 2022-12-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_student_pin'),
        ('bots', '0006_alter_bot_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now=True, verbose_name='Дата')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Балл')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='bots.bot', verbose_name='Бот')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='users.student', verbose_name='Учащийся')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ('-score',),
            },
        ),
    ]
