# Generated by Django 4.1.2 on 2023-02-16 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0014_alter_bot_last_rating"),
        ("users", "0006_student_pin"),
        ("stats", "0005_alter_rating_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateField(verbose_name="Дата")),
                ("score", models.PositiveSmallIntegerField(verbose_name="Балл")),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rerating",
                        to="bots.bot",
                        verbose_name="Бот",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rerating",
                        to="users.student",
                        verbose_name="Учащийся",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг",
                "verbose_name_plural": "Рейтинги",
                "ordering": ("-score",),
            },
        ),
    ]
