# Generated by Django 4.1.2 on 2022-11-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='log',
            name='category',
        ),
        migrations.RemoveField(
            model_name='log',
            name='student',
        ),
        migrations.RemoveField(
            model_name='log',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
