# Generated by Django 4.1.2 on 2022-11-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
