# Generated by Django 4.1.2 on 2022-11-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата выдачи'),
        ),
    ]
