# Generated by Django 4.1.2 on 2022-11-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
    ]
